from __future__ import annotations

import re

from agents import Agent, function_tool

from prompts import load_prompt
from tools.code_executor import execute_python
from tools.sql_runner import get_schema_description, run_sql


def safe_truncate(text: str, limit: int = 2000) -> str:
    if len(text) <= limit:
        return text
    return text[:limit] + f"\n... ({len(text) - limit} chars truncated)"


def clean_final_answer(text: str) -> str:
    cleaned = text
    cleaned = re.sub(
        r"```(?:python|py)[\s\S]*?```",
        "",
        cleaned,
        flags=re.IGNORECASE,
    )
    cleaned = re.sub(
        r"\s*\(?(?:see (?:filename|file):?|see below for visualization\.?)\s*`?[^`\n)]*`?\)?",
        "",
        cleaned,
        flags=re.IGNORECASE,
    )
    cleaned = re.sub(
        r"(?<!\()`?[\w.-]+\.(?:png|jpg|jpeg|gif|webp|svg)`?(?!\))",
        "",
        cleaned,
        flags=re.IGNORECASE,
    )
    cleaned = re.sub(r"\n{3,}", "\n\n", cleaned)
    cleaned = re.sub(r"\n[ \t]+\n", "\n\n", cleaned)
    return cleaned.strip()


def build_collector_input(resolved_request: str) -> str:
    return (
        "Stage 1 of 4: Data Collection.\n"
        "Collect only the data needed to answer the request.\n"
        "Do not provide the final answer.\n\n"
        f"Resolved user request:\n{resolved_request}"
    )


def build_analyst_input(resolved_request: str, collector_output: str) -> str:
    return (
        "Stage 2 of 4: Exploratory Data Analysis.\n"
        "Use the collected data below to compute findings, patterns, and caveats.\n"
        "Do not provide the final polished user answer yet.\n\n"
        f"Resolved user request:\n{resolved_request}\n\n"
        f"Collected data:\n{collector_output}"
    )


def build_hypothesis_input(
    resolved_request: str,
    collector_output: str,
    analyst_output: str,
) -> str:
    return (
        "Stage 3 of 4: Hypothesis and visualization.\n"
        "Use the collected data and analyst findings to form a hypothesis with evidence.\n"
        "Generate visualizations to support key findings.\n"
        "Do not worry about polishing the final output - that happens next.\n\n"
        f"Resolved user request:\n{resolved_request}\n\n"
        f"Collected data:\n{collector_output}\n\n"
        f"Analyst findings:\n{analyst_output}"
    )


def build_presenter_input(
    resolved_request: str,
    collector_output: str,
    analyst_output: str,
    hypothesis_output: str,
    existing_chart_paths: list[str] | None = None,
) -> str:
    parts = [
        "Stage 4 of 4: Final presentation.\n"
        "Transform the analysis into a polished, insight-driven answer for the user.\n"
        "Do NOT add new analysis - just present what was found in the best possible way.\n\n"
        f"Original user question:\n{resolved_request}\n\n"
        f"Collected data (raw query results):\n{safe_truncate(collector_output, 4000)}\n\n"
        f"Analyst findings:\n{analyst_output}\n\n"
        f"Hypothesis and evidence:\n{hypothesis_output}"
    ]
    if existing_chart_paths:
        chart_list = "\n".join(f"  - {path}" for path in existing_chart_paths)
        parts.append(
            f"\n\nCharts already generated by previous stages:\n{chart_list}\n"
            "Do NOT recreate these. Only create NEW presentation-quality visualizations "
            "that improve on these or add a different perspective. Aim for 2-3 charts total."
        )
    return "".join(parts)


def create_pipeline_agents(model_id: str) -> dict[str, Agent]:
    schema_desc = get_schema_description()

    collector_instructions = load_prompt("collector").format(SCHEMA_INFO=schema_desc)
    analyst_instructions = load_prompt("analyst").replace("{SCHEMA_INFO}", schema_desc)
    hypothesizer_instructions = load_prompt("hypothesizer").replace("{SCHEMA_INFO}", schema_desc)
    presenter_instructions = load_prompt("presenter").replace("{SCHEMA_INFO}", schema_desc)

    @function_tool
    def query_database(sql: str) -> str:
        """Execute a SQL query against the NYC Airbnb DuckDB database."""
        return run_sql(sql)

    @function_tool
    def run_analysis_code(code: str) -> str:
        """Execute Python code for exploratory data analysis."""
        return execute_python(code)

    @function_tool
    def create_visualization(code: str) -> str:
        """Execute Python code to generate data visualizations."""
        return execute_python(code, require_artifacts=True)

    collector = Agent(
        name="Data Collector",
        instructions=collector_instructions,
        tools=[query_database],
        model=model_id,
    )
    analyst = Agent(
        name="EDA Analyst",
        instructions=analyst_instructions,
        tools=[run_analysis_code, query_database],
        model=model_id,
    )
    hypothesizer = Agent(
        name="Hypothesis Generator",
        instructions=hypothesizer_instructions,
        tools=[create_visualization],
        model=model_id,
    )

    presenter_collector = Agent(
        name="Presenter Data Collector",
        instructions=(
            schema_desc + "\n\n"
            "You are assisting the Presenter agent. Run the SQL query needed to get "
            "the requested data, return the results, then hand off back to the Presenter.\n"
            "Do not attempt to generate charts in this sub-agent."
        ),
        tools=[query_database],
        model=model_id,
    )
    presenter_analyst = Agent(
        name="Presenter EDA Analyst",
        instructions=(
            "You are assisting the Presenter agent. Run the requested Python analysis, "
            "return the results, then hand off back to the Presenter.\n"
            "DATA_DIR and ARTIFACTS_DIR are pre-set variables available in your code."
        ),
        tools=[run_analysis_code],
        model=model_id,
    )
    presenter = Agent(
        name="Presenter",
        instructions=presenter_instructions,
        tools=[create_visualization],
        handoffs=[presenter_collector, presenter_analyst],
        model=model_id,
    )
    presenter_collector.handoffs = [presenter]
    presenter_analyst.handoffs = [presenter]

    return {
        "collector": collector,
        "analyst": analyst,
        "hypothesizer": hypothesizer,
        "presenter": presenter,
    }
