"use client";

import { useState } from "react";
import ReactMarkdown from "react-markdown";
import remarkGfm from "remark-gfm";
import ThinkingTrace from "./ThinkingTrace";
import type { TableSchema } from "./SqlQueryBlock";

export type TraceStep = {
  type: "agent_start" | "handoff" | "tool_call" | "tool_output" | "message";
  agent?: string;
  source?: string;
  target?: string;
  tool?: string;
  input?: string;
  output?: string;
  content?: string;
  ts: number;
  tables?: string[];
  row_count?: number;
  columns?: string[];
  preview?: Record<string, unknown>[];
  exit_code?: number;
  artifacts?: string[];
};

export type Message = {
  id: string;
  role: "user" | "assistant" | "status";
  content: string;
  artifacts?: string[];
  agent?: string;
  trace?: TraceStep[];
};

const BACKEND_URL = process.env.NEXT_PUBLIC_BACKEND_URL || "http://localhost:8000";

function getArtifactName(path: string): string {
  return path.split("/").pop() || path;
}

function isImageArtifact(path: string): boolean {
  return /\.(png|jpe?g|gif|webp|svg)$/i.test(path);
}

function ImageArtifact({
  artifactUrl,
  artifactName,
}: {
  artifactUrl: string;
  artifactName: string;
}) {
  const [failed, setFailed] = useState(false);

  return (
    <div className="rounded-lg overflow-hidden border border-[var(--color-border)] bg-[var(--color-surface-alt)]">
      {!failed ? (
        <img
          src={artifactUrl}
          alt={artifactName}
          className="w-full"
          loading="lazy"
          onError={() => setFailed(true)}
        />
      ) : (
        <div className="px-4 py-6 text-sm text-[var(--color-gray-warm)]">
          Preview unavailable for this chart.
        </div>
      )}
      <div className="flex items-center justify-between border-t border-[var(--color-border)] px-4 py-2 text-sm">
        <span className="font-medium text-[var(--color-navy)]">
          {artifactName}
        </span>
        <a
          href={artifactUrl}
          target="_blank"
          rel="noreferrer"
          className="text-[var(--color-coral)] hover:underline"
        >
          Open image
        </a>
      </div>
    </div>
  );
}

function ShareButton({
  message,
  userQuestion,
}: {
  message: Message;
  userQuestion?: string;
}) {
  const [copied, setCopied] = useState(false);

  const buildShareContent = (): string => {
    const lines: string[] = [];
    if (userQuestion) {
      lines.push(`Q: ${userQuestion}`, "");
    }
    lines.push(message.content);
    if (message.artifacts && message.artifacts.length > 0) {
      lines.push("", "Charts & Files:");
      for (const a of message.artifacts) {
        if (typeof a === "string" && a.length > 0) {
          lines.push(`- ${BACKEND_URL}${a}`);
        }
      }
    }
    lines.push("", "--- Generated by Airbnb Data Analyst");
    return lines.join("\n");
  };

  const handleShare = async () => {
    const text = buildShareContent();

    if (typeof navigator.share === "function") {
      try {
        await navigator.share({ title: "Airbnb Analysis", text });
        return;
      } catch {
        // User cancelled or API unavailable — fall through to clipboard
      }
    }

    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Clipboard also failed — select a hidden textarea as last resort
      const ta = document.createElement("textarea");
      ta.value = text;
      ta.style.position = "fixed";
      ta.style.opacity = "0";
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      document.body.removeChild(ta);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <button
      onClick={handleShare}
      className="share-btn mt-3 flex items-center gap-1.5 text-xs text-[var(--color-gray-warm)] hover:text-[var(--color-coral)] transition-colors duration-150"
    >
      {copied ? (
        <>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
            <polyline points="20 6 9 17 4 12" />
          </svg>
          Copied!
        </>
      ) : (
        <>
          <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <path d="M4 12v8a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2v-8" />
            <polyline points="16 6 12 2 8 6" />
            <line x1="12" y1="2" x2="12" y2="15" />
          </svg>
          Share
        </>
      )}
    </button>
  );
}

export default function MessageBubble({
  message,
  schema,
  userQuestion,
}: {
  message: Message;
  schema: Record<string, TableSchema> | null;
  userQuestion?: string;
}) {
  if (message.role === "status") {
    return (
      <div className="flex items-center gap-2 px-4 py-2 animate-fade-in-up">
        <div className="thinking-dots flex gap-1">
          <span className="w-1.5 h-1.5 rounded-full bg-[var(--color-teal)]" />
          <span className="w-1.5 h-1.5 rounded-full bg-[var(--color-teal)]" />
          <span className="w-1.5 h-1.5 rounded-full bg-[var(--color-teal)]" />
        </div>
        <span className="text-sm text-[var(--color-gray-warm)] italic">
          {message.agent && (
            <span className="font-semibold text-[var(--color-teal)] mr-1">
              {message.agent}:
            </span>
          )}
          {message.content}
        </span>
      </div>
    );
  }

  const isUser = message.role === "user";

  return (
    <div
      className={`flex animate-fade-in-up ${isUser ? "justify-end" : "justify-start"}`}
    >
      <div
        className={`max-w-[85%] rounded-2xl px-5 py-3.5 ${
          isUser
            ? "gradient-coral text-white rounded-br-md"
            : "bg-white border border-[var(--color-border)] rounded-bl-md shadow-sm"
        }`}
      >
        {isUser ? (
          <p className="text-[0.95rem] leading-relaxed">{message.content}</p>
        ) : (
          <div className="prose-chat text-[0.95rem]">
            <ReactMarkdown remarkPlugins={[remarkGfm]}>
              {message.content}
            </ReactMarkdown>
          </div>
        )}

        {message.artifacts && message.artifacts.length > 0 && (
          <div className="mt-4 space-y-3">
            {message.artifacts.filter((a): a is string => typeof a === "string" && a.length > 0).map((artifact, i) => {
              const artifactUrl = `${BACKEND_URL}${artifact}`;
              const artifactName = getArtifactName(artifact);

              if (isImageArtifact(artifact)) {
                return (
                  <ImageArtifact
                    key={i}
                    artifactUrl={artifactUrl}
                    artifactName={artifactName}
                  />
                );
              }

              return (
                <a
                  key={i}
                  href={artifactUrl}
                  target="_blank"
                  rel="noreferrer"
                  className="flex items-center justify-between rounded-lg border border-[var(--color-border)] bg-[var(--color-surface-alt)] px-4 py-3 text-sm hover:border-[var(--color-coral)]"
                >
                  <span className="font-medium text-[var(--color-navy)]">
                    {artifactName}
                  </span>
                  <span className="text-[var(--color-gray-warm)]">Open file</span>
                </a>
              );
            })}
          </div>
        )}

        {!isUser && (
          <ShareButton message={message} userQuestion={userQuestion} />
        )}

        {message.trace && message.trace.length > 0 && (
          <ThinkingTrace steps={message.trace} schema={schema} />
        )}
      </div>
    </div>
  );
}
